version: 2.1

orbs:  
  cypress: cypress-io/cypress@1
  node: circleci/node@2.1.1
jobs:
  test-build-deploy-feature:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm test -- --coverage
      - run:
          name: send code coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy draft to netlify, look for url in logs
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

workflows:
  test-build-deploy-production:
    jobs:
      - test-build-deploy-master:
        filters:
          branches:
            only: master

  test-build-deploy-draft:
      jobs: 
      - cypress/run 
      filters: 
      branches: 
      ignore: 
      - master        
