version: 2.1

orbs:  
  cypress: cypress-io/cypress@1.24.0
  node: circleci/node@2.1.1
jobs:
  test-build-deploy-master:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}
      - run:
          name: update npm
          command: npm install
      - run:
          name: start server
          command: npm start
      - run:
          name: name: cypress tests
          command: npx cypress run --record --key feba9e22-8635-4de9-bfb5-713553b446aa
      - run:
          name: send code coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: build
          command: npm run build
      - run:
          name: netlify production deploy
          command: ./node_modules/.bin/netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache

  test-build-deploy-feature:
    docker:
      - image: cypress/base:12
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: start server
          command: npm start
      - run:
          name: cypress tests
          command: npx cypress run --record --key feba9e22-8635-4de9-bfb5-713553b446aa
      - run:
          name: send code coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy draft to netlify, look for url in logs
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

workflows:
  test-build-deploy-production:
    jobs:
      - test-build-deploy-master:
          filters:
            branches:
              only: master

  test-build-deploy-draft:
    jobs:
      - test-build-deploy-feature:
          filters:
            branches:
              ignore: master





