version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test -- --coverage
            - run: npm run build
            - run: bash <(curl -s https://codecov.io/bash)
            - run: ./node_modules/.bin/netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
workflows:
  build-and-test:
    jobs:
      - build-and-test
